export const POKEMON_START_FETCH = 'POKEMON_START_FETCH';

export const POKEMONS_SUCCESS_FETCH = 'POKEMONS_SUCCESS_FETCH';
export const POKEMONS_FAIL_FETCH = 'POKEMONS_FAIL_FETCH';

export const POKEMON_SUCCESS_FETCH = 'POKEMON_SUCCESS_FETCH';
export const POKEMON_FAIL_FETCH = 'POKEMON_FAIL_FETCH';

export const POKEMON_LIKE_TOGGLE = 'POKEMON_LIKE_TOGGLE';
